# Basic
title: Yu
subtitle: A blog for Yu
welcome_message: <a href="https://github.com/stxupengyu" target="_blank">Click to my github</a>
description: Every single day without dancing is one day we betrayed of life.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://pangyu.club"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/stxupengyu?tab=repositories'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Yu
    # duoshuo: 
    
# Social
social:
    weibo: pangyuclub
    github: stxupengyu
    twitter: secret
    zhihu: people/xu-peng-yu-920
    mail: stxupengyu

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
